### ISSUE TITLE
Remove .idea from versionning

### ISSUE THREAD

**Issue by bcdbuddy** [alator21/Ding-time-to-work#1]
Or another way of saying it:
```bash
echo .idea >> .gitignore
```

**Comment by alator21** [comment]
Hi @bcdbuddy , and thanks for raising this issue. .idea folder and .iml file were added to gitignore.

**Comment by bcdbuddy** [comment]
Wonderful! I love your reactivity.

I also like your article in dev.to. Did you thought about turning it into an Alarm app?

**Comment by alator21** [comment]
I can think of many things, to upgrade this and make it like a more complete Alarm application. 
Some of them are:
1. Add additional syntax to JSON, so the user can add exclusion dates (e.g. the user wants the alarm to ring every weekday but  not 13/04/2020 because its a holiday)
2. Add additional syntax to JSON, so the user can add specific dates(normally the weekends it won't ring, but 12/04/2020 there is a special event)

So to answer your question, turning it into an alarm app is indeed in my thoughts and will probably raise some Github issues(todo) and start developing in the next days.
